#!/bin/bash

systemctl enable openstick-startup-diagnose.timer
systemctl enable openstick-button-monitor.service
systemctl enable openstick-gc-startup.service
systemctl enable openstick-sim-changer.service
systemctl enable regenerate-ssh-host-keys.service
systemctl enable openstick-expanddisk-startup.service

echo "install complete!"
exit 0
