#!/bin/bash

echo "Try to enable installed services"

for serv in openstick-startup-diagnose.timer openstick-button-monitor.service openstick-gc-startup.service openstick-sim-changer.service regenerate-ssh-host-keys.service openstick-expanddisk-startup.service; do
  if [ -e "/etc/systemd/system/$serv" ]; then
    systemctl enable $serv
  fi
done

exit 0
